name: ROS Noetic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  industrial_ci:
    name: ROS Noetic (${{ matrix.ros_repo }})
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [ noetic ]
        ros_repo: [ main ]

    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      DOCKER_IMAGE: "ruansp/ubuntu-20.04:cfc-ros"

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
        
      - name: Checkout submodules
        run: |
          git config --global --add safe.directory '*'
          git submodule update --init --recursive

      - name: ccache cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          # we always want the ccache cache to be persisted, as we cannot easily
          # determine whether dependencies have changed, and ccache will manage
          # updating the cache for us. Adding 'run_id' to the key will force an
          # upload at the end of the job.
          key: ccache-${{ matrix.ros_distro }}-${{ matrix.ros_repo }}-${{github.run_id}}
          restore-keys: |
            ccache-${{ matrix.ros_distro }}-${{ matrix.ros_repo }}
            
      - name: Run industrial_ci
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: ${{ matrix.ros_repo }}
